### ISSUE TITLE
Cannot Confirm Sell Command with version 1.3

### ISSUE THREAD

**Issue by NiteKat** [ZehsTeam/Lethal-Company-SellMyScrap#1]
I updated the mod through r2modman to version 1.3 and suddenly I cannot confirm selling anymore. I even created a profile with only this mod and its dependencies, and the same behavior happens.

![image](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/assets/28605404/2b60a170-248e-4566-8a19-d17ec238cffc)
![image](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/assets/28605404/a399a689-215a-41b9-a639-c586d4180f0e)

Even if I try just "c" or in all caps, etc., you are unable to confirm selling anymore.

**Comment by ZehsTeam** [comment]
Could you send me your log file?

**Comment by ZehsTeam** [comment]
@NiteKat This problem should now be fixed in [v1.3.1](https://thunderstore.io/c/lethal-company/p/Zehs/SellMyScrap/)

**Comment by NiteKat** [comment]
Can confirm, issue is fixed in 1.3.1. :)
