### ISSUE TITLE
[Bug] Sometimes does not calculate "sell quota" correctly

### ISSUE THREAD

**Issue by JohnMetroid** [ZehsTeam/Lethal-Company-SellMyScrap#10]
hi there,

this issue has popped up occasionally with recent versions.  Usually, "sell quota" will find the right value.  Occasionally, it will find items that sell for 1 credit too little

![image](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/assets/139426529/0f86b43b-f94f-40da-8215-f5c0dc353bec)

**Comment by ZehsTeam** [comment]
@ajsglist This happened because there was no possible set of items that total $130 and my sell algorithm doesn't like to oversell. I do want to try and fix this issue in a future update where it'll sell for a little bit extra if an exact amount cannot be found.

**Comment by JohnMetroid** [comment]
yeah, an option to force oversell instead of undersell would be great in the future

thanks!

**Comment by ZehsTeam** [comment]
@ajsglist I will look into adding that when I get the chance.

**Comment by ZehsTeam** [comment]
@ajsglist This has been fixed in the latest update [SellMyScrap v1.6.0](https://thunderstore.io/c/lethal-company/p/Zehs/SellMyScrap/) - [c75eb15](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/commit/c75eb15a712a9d9a5cbbd1f4002051d714f22e3b)
