### ISSUE TITLE
[Compatibility] Compatibility with ShipInventory

### ISSUE THREAD

**Issue by Koishukaze** [ZehsTeam/Lethal-Company-SellMyScrap#12]
Is compatibility with [ShipInventory](https://thunderstore.io/c/lethal-company/p/WarperSan/ShipInventory/) possible?

**Comment by ZehsTeam** [comment]
@Koishukaze  Possibly, I'll look into it later if I remember.

**Comment by ZehsTeam** [comment]
@Koishukaze Compatibility with the [ShipInventory](https://thunderstore.io/c/lethal-company/p/WarperSan/ShipInventory/) mod has been added in the latest update [SellMyScrap v1.7.0](https://thunderstore.io/c/lethal-company/p/Zehs/SellMyScrap/) - [cef3cd5](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/commit/cef3cd5b5bd213fc2f9b6bbed409bb750746a032)
