### ISSUE TITLE
[Request] config option to ignore scrap worth 0

### ISSUE THREAD

**Issue by JohnMetroid** [ZehsTeam/Lethal-Company-SellMyScrap#2]
There's at least one way to get scrap worth 0 (LethalCasino), and by default SellMyScrap will add them to every sale.  If possible, it would be great to get a config option to prevent selling 0 credit scrap (leaving the players to sell it manually or leave it behind if they don't want it)

Thanks for the consideration

**Comment by ZehsTeam** [comment]
@ajsglist Yeah, I could add that. I didn't realize that was a problem hehe.

**Comment by ZehsTeam** [comment]
This has been added in [v1.3.2](https://thunderstore.io/c/lethal-company/p/Zehs/SellMyScrap/)
