### ISSUE TITLE
[Request] Config option to disable "edit config" terminal command

### ISSUE THREAD

**Issue by JohnMetroid** [ZehsTeam/Lethal-Company-SellMyScrap#3]
I'm generally concerned about client desyncs, and this seems like a potential issue in lobbies.  Moreover, it's not something I would expect our group to use during a game.

Is it possible to get a config option to disable this command?

Thanks for the consideration

**Comment by ZehsTeam** [comment]
@ajsglist There shouldn't be any desync problems. Only **Sell Settings** and **Advanced Sell Settings** are synced to all clients from the host. Only the host can change these settings in the terminal config editor. The changes get sent to all clients whenever the host changes synced config settings. Clients will also receive the synced config settings from the host whenever they join the game.

The config editor is mainly used for making changes to the `dontSellListJson` config setting.
With this, you can specify any scrap item you don't want the sell algorithm to use. (This works with modded scrap items)

However, I will consider adding this as a config setting.

And if you do experience any desync problems, please let me know.
