### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by mrakrmakmrka** [ZehsTeam/Lethal-Company-SellMyScrap#6]
If this mod is installed, no player can connect to my lobby.

**Comment by ZehsTeam** [comment]
@mrakrmakmrka Can you please send your modpack code and BepInEx `LogOutput.log` file?

**Comment by mrakrmakmrka** [comment]
@ZehsTeam my modpack code: 018ed052-2707-2f30-18da-105d875d6628 
[logout.txt](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/files/14953587/logout.txt)

**Comment by ZehsTeam** [comment]
@mrakrmakmrka I forgot to ask, are you playing on v49 or the v50 public beta? I just tested your modpack on the latest patch of the v50 public beta and can have clients connect without issues.

**Comment by mrakrmakmrka** [comment]
@ZehsTeam I'm playing on version 49.

**Comment by ZehsTeam** [comment]
@mrakrmakmrka I tested your modpack with my mod on version 49 and had no issues with other clients connecting to my lobby. Unless you have logs with errors from my mod stopping other clients from connecting to your lobby, it's not my mod causing the issue.

**Comment by mrakrmakmrka** [comment]
@ZehsTeam I tried to play only with your mod, no one can join me. i installed a new profile, reinstalled mod manager, still no one can join....
It keeps writing this in the table: 
[Warning: Unity Log] [Netcode] NetworkConfig mismatch. The configuration between the server and client does not match
[Info :LobbyControl] 2 disconnected
[Info : Unity Log] Disconnect callback called
[Info : Unity Log] Is server: True; ishost: True; isConnectedClient: True
[Info : Unity Log] Disconnect callback called in gamenetworkmanager; disconnecting clientId: 2
[Info : Unity Log] A Player disconnected but they were not in clientplayerlist

If your mod is not installed on other players - they can't get in. 
The mod is good, but it doesn't work for me, I have to delete it.

**Comment by ZehsTeam** [comment]
@mrakrmakmrka This mod is for all clients. My mod has networking and special events, so **ALL players must have it installed!**
