### ISSUE TITLE
Conflict with Quota Rollover

### ISSUE THREAD

**Issue by KiichiT** [ZehsTeam/Lethal-Company-SellMyScrap#7]
I'm not sure what specifically is the issue is on the coding side but it's a replicable issue with both mods (Quota Rollover by boxofbiscuits97 and this one) enabled. The issue is that, regardless of how many days are left, as long as the rollover quantity is greater than the quota, it would proceeded to the next quota. 

Quota Rollover [boxofbiscuits97](https://thunderstore.io/c/lethal-company/p/boxofbiscuits97/)

**Comment by ZehsTeam** [comment]
@KiichiT Set the `overrideSetNewProfitQuota` config setting to `false`. This should fix your issue.

**Comment by ZehsTeam** [comment]
This has now been fixed by default in the latest release v1.5.13+, [82f8e31](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/commit/82f8e31591c48b35c6759666b8f97f38a83fd7f8)
